### ISSUE TITLE
brew install awsebcli error

### ISSUE THREAD

**Issue by bounlu** [awsdocs/aws-elastic-beanstalk-developer-guide#116]
Installing `awsebcli` via `homebrew` works fine, but cannot verify the installation:

```
$ brew install awsebcli
==> Downloading https://ghcr.io/v2/homebrew/core/aws-elasticbeanstalk/manifests/3.20.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/aws-elasticbeanstalk/blobs/sha256:5a8269756245372ef47b8367d95e22dea139a6bf75ef7bddb9e0f68f328a8274
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5a8269756245372ef47b8367d95e22dea139a6bf75ef7bddb9e0f68f328a8274?se=2021
######################################################################## 100.0%
==> Pouring aws-elasticbeanstalk--3.20.0.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/aws-elasticbeanstalk/3.20.0: 2,768 files, 73.5MB

$ eb --version
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'enum' has no attribute 'IntFlag'
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 3, in <module>
    import re
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by bounlu** [comment]
found the solution here:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag
